// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ka.workoutsum.domain;

import com.ka.workoutsum.domain.Exercise;
import com.ka.workoutsum.domain.ExerciseDataOnDemand;
import com.ka.workoutsum.domain.ExerciseLogRec;
import com.ka.workoutsum.domain.ExerciseLogRecDataOnDemand;
import com.ka.workoutsum.domain.WeightWorkoutLogRec;
import com.ka.workoutsum.domain.WeightWorkoutLogRecDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExerciseLogRecDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExerciseLogRecDataOnDemand: @Component;
    
    private Random ExerciseLogRecDataOnDemand.rnd = new SecureRandom();
    
    private List<ExerciseLogRec> ExerciseLogRecDataOnDemand.data;
    
    @Autowired
    private ExerciseDataOnDemand ExerciseLogRecDataOnDemand.exerciseDataOnDemand;
    
    @Autowired
    private WeightWorkoutLogRecDataOnDemand ExerciseLogRecDataOnDemand.weightWorkoutLogRecDataOnDemand;
    
    public ExerciseLogRec ExerciseLogRecDataOnDemand.getNewTransientExerciseLogRec(int index) {
        ExerciseLogRec obj = new ExerciseLogRec();
        setExercise(obj, index);
        setWorkoutLogRec(obj, index);
        return obj;
    }
    
    public void ExerciseLogRecDataOnDemand.setExercise(ExerciseLogRec obj, int index) {
        Exercise exercise = exerciseDataOnDemand.getRandomExercise();
        obj.setExercise(exercise);
    }
    
    public void ExerciseLogRecDataOnDemand.setWorkoutLogRec(ExerciseLogRec obj, int index) {
        WeightWorkoutLogRec workoutLogRec = weightWorkoutLogRecDataOnDemand.getRandomWeightWorkoutLogRec();
        obj.setWorkoutLogRec(workoutLogRec);
    }
    
    public ExerciseLogRec ExerciseLogRecDataOnDemand.getSpecificExerciseLogRec(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ExerciseLogRec obj = data.get(index);
        Long id = obj.getId();
        return ExerciseLogRec.findExerciseLogRec(id);
    }
    
    public ExerciseLogRec ExerciseLogRecDataOnDemand.getRandomExerciseLogRec() {
        init();
        ExerciseLogRec obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ExerciseLogRec.findExerciseLogRec(id);
    }
    
    public boolean ExerciseLogRecDataOnDemand.modifyExerciseLogRec(ExerciseLogRec obj) {
        return false;
    }
    
    public void ExerciseLogRecDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ExerciseLogRec.findExerciseLogRecEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ExerciseLogRec' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ExerciseLogRec>();
        for (int i = 0; i < 10; i++) {
            ExerciseLogRec obj = getNewTransientExerciseLogRec(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
