// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ka.workoutsum.domain;

import com.ka.workoutsum.domain.Exercise;
import com.ka.workoutsum.domain.ExerciseDataOnDemand;
import com.ka.workoutsum.domain.Muscle;
import com.ka.workoutsum.domain.MuscleDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ExerciseDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ExerciseDataOnDemand: @Component;
    
    private Random ExerciseDataOnDemand.rnd = new SecureRandom();
    
    private List<Exercise> ExerciseDataOnDemand.data;
    
    @Autowired
    private MuscleDataOnDemand ExerciseDataOnDemand.muscleDataOnDemand;
    
    public Exercise ExerciseDataOnDemand.getNewTransientExercise(int index) {
        Exercise obj = new Exercise();
        setName(obj, index);
        setTargetedMuscle(obj, index);
        return obj;
    }
    
    public void ExerciseDataOnDemand.setName(Exercise obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ExerciseDataOnDemand.setTargetedMuscle(Exercise obj, int index) {
        Muscle targetedMuscle = muscleDataOnDemand.getRandomMuscle();
        obj.setTargetedMuscle(targetedMuscle);
    }
    
    public Exercise ExerciseDataOnDemand.getSpecificExercise(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Exercise obj = data.get(index);
        Long id = obj.getId();
        return Exercise.findExercise(id);
    }
    
    public Exercise ExerciseDataOnDemand.getRandomExercise() {
        init();
        Exercise obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Exercise.findExercise(id);
    }
    
    public boolean ExerciseDataOnDemand.modifyExercise(Exercise obj) {
        return false;
    }
    
    public void ExerciseDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Exercise.findExerciseEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Exercise' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Exercise>();
        for (int i = 0; i < 10; i++) {
            Exercise obj = getNewTransientExercise(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
