// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ka.workoutsum.domain;

import com.ka.workoutsum.domain.WeightWorkout;
import com.ka.workoutsum.domain.WeightWorkoutDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WeightWorkoutDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WeightWorkoutDataOnDemand: @Component;
    
    private Random WeightWorkoutDataOnDemand.rnd = new SecureRandom();
    
    private List<WeightWorkout> WeightWorkoutDataOnDemand.data;
    
    public WeightWorkout WeightWorkoutDataOnDemand.getNewTransientWeightWorkout(int index) {
        WeightWorkout obj = new WeightWorkout();
        setCreateTime(obj, index);
        setGoal(obj, index);
        return obj;
    }
    
    public void WeightWorkoutDataOnDemand.setCreateTime(WeightWorkout obj, int index) {
        Long createTime = new Integer(index).longValue();
        obj.setCreateTime(createTime);
    }
    
    public void WeightWorkoutDataOnDemand.setGoal(WeightWorkout obj, int index) {
        String goal = "goal_" + index;
        obj.setGoal(goal);
    }
    
    public WeightWorkout WeightWorkoutDataOnDemand.getSpecificWeightWorkout(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WeightWorkout obj = data.get(index);
        Long id = obj.getId();
        return WeightWorkout.findWeightWorkout(id);
    }
    
    public WeightWorkout WeightWorkoutDataOnDemand.getRandomWeightWorkout() {
        init();
        WeightWorkout obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WeightWorkout.findWeightWorkout(id);
    }
    
    public boolean WeightWorkoutDataOnDemand.modifyWeightWorkout(WeightWorkout obj) {
        return false;
    }
    
    public void WeightWorkoutDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WeightWorkout.findWeightWorkoutEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WeightWorkout' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WeightWorkout>();
        for (int i = 0; i < 10; i++) {
            WeightWorkout obj = getNewTransientWeightWorkout(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
