// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ka.workoutsum.domain;

import com.ka.workoutsum.domain.CardioWorkout;

privileged aspect CardioWorkout_Roo_JavaBean {
    
    public String CardioWorkout.getType() {
        return this.type;
    }
    
    public void CardioWorkout.setType(String type) {
        this.type = type;
    }
    
}
