// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ka.workoutsum.domain;

import com.ka.workoutsum.domain.Muscle;

privileged aspect Muscle_Roo_JavaBean {
    
    public String Muscle.getName() {
        return this.name;
    }
    
    public void Muscle.setName(String name) {
        this.name = name;
    }
    
}
